title: "JUXI"
email: "hello@juxi-ai.com"
description: >- # this means to ignore newlines until "baseurl:"
  Juxi Empowers small business owners with their own AI C-Suite executives, enabling ideation and collaboration for strategic decision-making and driving innovative solutions
baseurl: "" # the subpath of your site, e.g. /blog
author: "JUXI AI"
keywords: "AI, JUXI, GenAI, Mentor, C-Suite, Artificial Intelligence"
url: "https://juxi-ai.com"

# Google Analytics
google_analytics: "G-R2Z2VWPQ26"


# General Settings
logo_url: "/assets/images/logo.png"
#logo_url_2: "/assets/images/white_logo.png"


#facebook_url: "https://www.facebook.com/"
#twitter_url: "https://twitter.com/"
#youtube_url: "https://www.youtube.com/"
#instagram_url: "https://www.instagram.com/"
linkedin_url: "https://www.linkedin.com/company/juxi/"

form_action_url: "https://formsubmit.io/send/hello@juxi-ai.com"

permalink: "/:title"

#collections
collections:
  about:
    output: true
  product:
    output: true
  team:
    output: true
