title: "JUXI AI"
email: "hello@juxi-ai.com"
description: >- # this means to ignore newlines until "baseurl:"
  Litmus is a modern presentation Jekyll Portfolio Template.
baseurl: "" # the subpath of your site, e.g. /blog
author: "JUXI AI"
keywords: "AI, JUXI, GenAI, Mentor, C-Suite, Artificial Intelligence"
url: "https://juxi-ai.com"

# Google Analytics
google_analytics: ""


# General Settings
logo_url: "/assets/images/logo.png"
logo_url_2: "/assets/images/white_logo.png"


#facebook_url: "https://www.facebook.com/"
#twitter_url: "https://twitter.com/"
#youtube_url: "https://www.youtube.com/"
#instagram_url: "https://www.instagram.com/"

form_action_url: "https://formsubmit.io/send/hello@juxi-ai.com"

permalink: "/:title"

#collections
collections:
  features:
    output: true
  services:
    output: true
  portfolios:
    output: true
